[package]
name = "irust"
version = "1.2.2"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = { version = "0.18.2", features = ["serde"] }
dirs-next = "2.0.0"
once_cell = "1.5.2"
toml = "0.5.8"
serde = { version = "1.0.118", features = ["derive"] }

[target.'cfg(unix)'.dependencies]
nix = "0.19.1"

[features]
ui-test = []

# flamegraph
# [profile.release]
# debug = true
