[package]
name = "irust"
version = "0.7.4"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = "0.9.6"
dirs = "2.0.1"
once_cell = "0.2.4"

[dependencies.syntect]
version = "3.2.0"
default-features = false
features = ["parsing", "assets", "dump-load-rs"]

[target.'cfg(unix)'.dependencies]
nix = "0.14.1"
