[package]
name = "irust"
version = "0.8.9"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = "0.17.5"
dirs-next = "1.0.1"
once_cell = "1.4.0"

[target.'cfg(unix)'.dependencies]
nix = "0.17.0"
