[package]
name = "irust"
version = "0.5.8"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
dirs = "2.0.1"
syntect = { version = "3.2.0", optional = true }

[dependencies.crossterm]
git = "https://github.com/sigmaSd/crossterm"
branch = "fork"

[target.'cfg(unix)'.dependencies]
nix = "0.14.1"

[features]
highlight = ["syntect"]

