[package]
name = "irust"
version = "0.7.4"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = "0.10.2"
dirs = "2.0.2"
once_cell = "1.0.2"

[dependencies.syntect]
version = "3.2.1"
default-features = false
features = ["parsing", "assets", "dump-load-rs"]

[target.'cfg(unix)'.dependencies]
nix = "0.15.0"
