[package]
name = "irust"
version = "0.4.2"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = {git = "https://github.com/sigmaSd/crossterm"}
dirs = "1.0.5"

[target.'cfg(unix)'.dependencies]
nix = "0.13.0"

