[package]
name = "irust"
version = "0.9.5"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = { version = "0.18.2", features = ["serde"] }
dirs-next = "2.0.0"
once_cell = "1.5.2"
toml = "0.5.7"
serde = { version = "1.0.117", features = ["derive"] }
notify = "4.0.15"

[target.'cfg(unix)'.dependencies]
nix = "0.19.0"
