[package]
name = "irust"
version = "0.8.14"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = { version = "0.17.8", features = ["serde"] }
dirs-next = "1.0.1"
once_cell = "1.4.1"
toml = "0.5.6"
serde = { version = "1.0.115", features = ["derive"] }

[target.'cfg(unix)'.dependencies]
nix = "0.18.0"
