[package]
name = "irust"
version = "0.8.6"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = "0.17.5"
dirs = "2.0.2"
once_cell = "1.4.0"

[dependencies.syntect]
version = "4.2.0"
default-features = false
features = ["parsing", "assets", "dump-load-rs", "regex-fancy"]

[target.'cfg(unix)'.dependencies]
nix = "0.17.0"
