[package]
name = "irust_api"
version = "0.2.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
description = "IRust API"
repository = "https://github.com/sigmaSd/IRust/tree/master/crates/irust_api"
license = "MIT"

[dependencies]
serde = {version = "1.0.125", features = ["derive"]}
